### ISSUE TITLE
"In CSS2, the media type in @media is mandatory"

### ISSUE THREAD

**Issue by strarsis** [w3c/Unicorn#208]
Whatever `@media` I am using, the validator always complains about it:
````
In CSS2, the media type in @media is mandatory
````

```css
@media screen and (min-width: 480px) {
  body {
    background-color: red;
  }
}
````
The CSS styles above look fine to me.
